export const TextButtons = [
  'paragraphFormat',
  'bold',
  'italic',
  'underline',
  'strikeThrough',
  'subscript',
  'superscript',
  'fontFamily',
  'fontSize',
  'textColor',
  'backgroundColor',
  'inlineClass',
  'inlineStyle',
  'clearFormatting',
  'quote',
  'code',
];
