export const enum FroalaPlugin {
  Align = 'align',
  Colors = 'colors',
  Image = 'image',
  Link = 'link',
  Lists = 'lists',
  ParagraphFormat = 'paragraph_format',
  Table = 'table',
  Url = 'url',
  Video = 'video',
  Quote = 'quote',
  Draggable = 'draggable',
  FontSize = 'font_size',
  QuickInsert = 'quick_insert',
}
